fragment HomeParts on Home {
  __typename
  heroImage
  heroHeading
  heroSubtext
  heroCTALabel
  heroBottomCTALabel
  ctaHeading
  ctaBody
  aboutHeading
  aboutImage
  aboutCredentialTitle
  aboutBody
  feelLikeYouHeading
  feelLikeYouTagline
  feelLikeYouQuestions
  servicesHeading
  servicesSubtext
  services {
    __typename
    title
    description
    icon
    href
    buttonLabel
    colorScheme
  }
  bottomCTAText
}

fragment ServicesParts on Services {
  __typename
  heroHeading
  heroSubtext
  services {
    __typename
    title
    duration
    description
    icon
    href
    buttonLabel
    highlights
    isThisForYou
    colorScheme
  }
  ctaHeading
  ctaSubtext
  ctaButtonLabel
}

fragment AboutParts on About {
  __typename
  heroHeading
  heroSubtext
  storyHeading
  storyBody
  credentialsHeading
  credentialsSubtext
  credentials {
    __typename
    icon
    title
    description
    gradient
  }
  valuesHeading
  valuesSubtext
  values {
    __typename
    icon
    title
    description
  }
}

fragment ClarityCoachingParts on ClarityCoaching {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  heroCTALabel
  heroSideEmoji
  heroSideWeeks
  heroSideSubtext
  resultsHeadingPrefix
  resultsHeadingHighlight
  resultsSubtext
  perhapsLabel
  perhapsItems {
    __typename
    emoji
    text
    borderColor
  }
  bannerText
  bannerHighlight
  missingPieceHeadingPrefix
  missingPieceHeadingHighlight
  problemTitle
  problemBody
  solutionTitle
  solutionBody
  solutionWord
  philosophyLabel
  philosophyHeadingPrefix
  philosophyHeadingHighlight
  philosophyQuote
  philosophyBody
  philosophyBannerPrefix
  philosophyBannerHighlight
  philosophyClosingPrefix
  philosophyClosingHighlight
  timelineLabel
  timelineHeadingPrefix
  timelineHeadingHighlight
  timelineSubtext
  timelineSteps {
    __typename
    number
    weeks
    title
    subtitle
    description
    accent
  }
  timelineCTALabel
  experienceLabel
  experienceHeadingPrefix
  experienceHeadingHighlight
  experienceItems {
    __typename
    emoji
    title
    subtitle
    bg
  }
  bonusEmoji
  bonusPrefix
  bonusText
  ctaSectionHeadingPrefix
  ctaSectionHeadingHighlight
  ctaSectionBody
  ctaButtonLabel
}

fragment CareerCoachingParts on CareerCoaching {
  __typename
  heroHeading
  heroSubtext
  heroCTALabel
  resultsHeadingPrefix
  resultsHeadingHighlight
  resultsSubtext
  perhapsLabel
  situations
  bannerPrefix
  bannerHighlight
  clarityHeadingPrefix
  clarityHeadingHighlight
  clarityBody
  clarityBigWord
  philosophyHeadingPrefix
  philosophyHeadingHighlight
  philosophyBody
  imagineHeadingHighlight
  imagineItems {
    __typename
    emoji
    text
    borderColor
    bg
  }
  roadmapHeadingPrefix
  roadmapHeadingHighlight
  roadmapSubtext1
  roadmapSubtext2
  roadmapSteps {
    __typename
    number
    weeks
    title
    subtitle
    subtitleColor
    description
  }
  roadmapCTALabel
  experienceHeadingPrefix
  experienceHeadingHighlight
  experienceSubtext
  experienceItems
  ctaSectionHeadingPrefix
  ctaSectionHeadingHighlight
  ctaSectionBody
  ctaButtonLabel
}

fragment NumerologyParts on Numerology {
  __typename
  heroBadge
  heroHeading
  heroTagline
  heroSubtext
  heroCTALabel
  selfDiscoveryHeadingPrefix
  selfDiscoveryHeadingHighlight
  selfDiscoverySubtext
  selfDiscoveryItems {
    __typename
    emoji
    text
    borderColor
  }
  selfDiscoveryStatementPrefix
  selfDiscoveryStatementHighlight
  whatIsLabel
  whatIsHeadingPrefix
  whatIsHeadingHighlight
  whatIsIsntParagraph
  whatIsIsBody
  processLabel
  processHeadingPrefix
  processHeadingHighlight
  processSteps {
    __typename
    emoji
    stepLabel
    title
    description
  }
  includesLabel
  includesHeadingPrefix
  includesHeadingHighlight
  includesSubtext
  includes {
    __typename
    emoji
    title
    description
  }
  philosophyLabel
  philosophyHeadingPrefix
  philosophyHeadingHighlight
  philosophyQuote
  philosophyBody
  philosophyBanner
  philosophyClosingPrefix
  philosophyClosingHighlight
  ctaSectionHeading
  ctaButtonLabel
}

fragment ResourcesParts on Resources {
  __typename
  heroBadge
  heroHeading
  heroHeadingHighlight
  heroSubtext
  featuredHeading
  featuredPosts {
    __typename
    post {
      ... on Post {
        __typename
        title
        publishedAt
        status
        excerpt
        image
        icon
        iconColor
        gradient
        badgeColor
        body
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
  featuredPodcasts {
    __typename
    podcast {
      ... on Podcast {
        __typename
        title
        episode
        publishedAt
        status
        audioUrl
        excerpt
        image
        icon
        gradient
        badgeColor
        body
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
  }
  blogLibraryHeading
  podcastLibraryHeading
  newsletterHeading
  newsletterSubtext
  newsletterPlaceholder
  newsletterButton
  newsletterSuccessMessage
}

fragment ContactParts on Contact {
  __typename
  heroImage
  heroHeading
  heroSubtext
  sectionHeading
  sectionSubtext
  email
  phone
  videoText
  location
  bookingCTALabel
  formHeading
}

fragment PostParts on Post {
  __typename
  title
  publishedAt
  status
  excerpt
  image
  icon
  iconColor
  gradient
  badgeColor
  body
}

fragment PodcastParts on Podcast {
  __typename
  title
  episode
  publishedAt
  status
  audioUrl
  excerpt
  image
  icon
  gradient
  badgeColor
  body
}

fragment NavbarParts on Navbar {
  __typename
  brandLabel
  ctaLabel
  links {
    __typename
    label
    href
    showDropdown
  }
  workWithMeDropdown {
    __typename
    label
    href
  }
}

fragment BookingFormParts on BookingForm {
  __typename
  overlayTitle
  firstNameLabel
  lastNameLabel
  emailLabel
  countryCodeLabel
  phoneLabel
  serviceLabel
  messageLabel
  messagePlaceholder
  submitLabel
  submittingLabel
  successMessage
  errorMessage
  services
}

fragment FooterParts on Footer {
  __typename
  brandHeading
  brandDescription
  quickLinksHeading
  quickLinks {
    __typename
    label
    href
  }
  servicesHeading
  serviceLinks {
    __typename
    label
    href
  }
  connectHeading
  socialLinks {
    __typename
    label
    icon
    href
  }
  emailLabel
  email
  phoneLabel
  phone
  copyright
}

fragment TypographyParts on Typography {
  __typename
  headingFont
  headingWeight
  headingStyle
  bodyFont
  bodyWeight
  baseFontSize
}

fragment TestimonialsParts on Testimonials {
  __typename
  items {
    __typename
    quote
    author
  }
}
