//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  about: About;
  aboutConnection: AboutConnection;
  clarityCoaching: ClarityCoaching;
  clarityCoachingConnection: ClarityCoachingConnection;
  careerCoaching: CareerCoaching;
  careerCoachingConnection: CareerCoachingConnection;
  numerology: Numerology;
  numerologyConnection: NumerologyConnection;
  resources: Resources;
  resourcesConnection: ResourcesConnection;
  contact: Contact;
  contactConnection: ContactConnection;
  testimonials: Testimonials;
  testimonialsConnection: TestimonialsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryClarityCoachingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryClarityCoachingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClarityCoachingFilter>;
};


export type QueryCareerCoachingArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCareerCoachingConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerCoachingFilter>;
};


export type QueryNumerologyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNumerologyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NumerologyFilter>;
};


export type QueryResourcesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResourcesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourcesFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};


export type QueryTestimonialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  about?: InputMaybe<AboutFilter>;
  clarityCoaching?: InputMaybe<ClarityCoachingFilter>;
  careerCoaching?: InputMaybe<CareerCoachingFilter>;
  numerology?: InputMaybe<NumerologyFilter>;
  resources?: InputMaybe<ResourcesFilter>;
  contact?: InputMaybe<ContactFilter>;
  testimonials?: InputMaybe<TestimonialsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | About | ClarityCoaching | CareerCoaching | Numerology | Resources | Contact | Testimonials | Folder;

export type Home = Node & Document & {
  __typename?: 'Home';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroHeadingHighlight?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  heroCTALabel?: Maybe<Scalars['String']['output']>;
  aboutBadge?: Maybe<Scalars['String']['output']>;
  aboutHeading?: Maybe<Scalars['String']['output']>;
  aboutParagraph1?: Maybe<Scalars['String']['output']>;
  aboutParagraph2?: Maybe<Scalars['String']['output']>;
  aboutParagraph3?: Maybe<Scalars['String']['output']>;
  aboutQuote?: Maybe<Scalars['String']['output']>;
  aboutCTALabel?: Maybe<Scalars['String']['output']>;
  servicesSectionHeading?: Maybe<Scalars['String']['output']>;
  servicesSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroHeadingHighlight?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  heroCTALabel?: InputMaybe<StringFilter>;
  aboutBadge?: InputMaybe<StringFilter>;
  aboutHeading?: InputMaybe<StringFilter>;
  aboutParagraph1?: InputMaybe<StringFilter>;
  aboutParagraph2?: InputMaybe<StringFilter>;
  aboutParagraph3?: InputMaybe<StringFilter>;
  aboutQuote?: InputMaybe<StringFilter>;
  aboutCTALabel?: InputMaybe<StringFilter>;
  servicesSectionHeading?: InputMaybe<StringFilter>;
  servicesSectionSubtext?: InputMaybe<StringFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type AboutCredentials = {
  __typename?: 'AboutCredentials';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type AboutValues = {
  __typename?: 'AboutValues';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  desc?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  bioParagraph1?: Maybe<Scalars['String']['output']>;
  bioParagraph2?: Maybe<Scalars['String']['output']>;
  bioParagraph3?: Maybe<Scalars['String']['output']>;
  bioParagraph4?: Maybe<Scalars['String']['output']>;
  credentialsSectionHeading?: Maybe<Scalars['String']['output']>;
  credentials?: Maybe<Array<Maybe<AboutCredentials>>>;
  valuesSectionHeading?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<AboutValues>>>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutCredentialsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type AboutValuesFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  desc?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  bioParagraph1?: InputMaybe<StringFilter>;
  bioParagraph2?: InputMaybe<StringFilter>;
  bioParagraph3?: InputMaybe<StringFilter>;
  bioParagraph4?: InputMaybe<StringFilter>;
  credentialsSectionHeading?: InputMaybe<StringFilter>;
  credentials?: InputMaybe<AboutCredentialsFilter>;
  valuesSectionHeading?: InputMaybe<StringFilter>;
  values?: InputMaybe<AboutValuesFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ClarityCoachingPerhapsItems = {
  __typename?: 'ClarityCoachingPerhapsItems';
  emoji?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
};

export type ClarityCoaching = Node & Document & {
  __typename?: 'ClarityCoaching';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  sectionHeading?: Maybe<Scalars['String']['output']>;
  sectionSubtext?: Maybe<Scalars['String']['output']>;
  perhapsItems?: Maybe<Array<Maybe<ClarityCoachingPerhapsItems>>>;
  bannerQuote?: Maybe<Scalars['String']['output']>;
  outcomesSectionHeading?: Maybe<Scalars['String']['output']>;
  outcomes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ClarityCoachingPerhapsItemsFilter = {
  emoji?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type ClarityCoachingFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  sectionHeading?: InputMaybe<StringFilter>;
  sectionSubtext?: InputMaybe<StringFilter>;
  perhapsItems?: InputMaybe<ClarityCoachingPerhapsItemsFilter>;
  bannerQuote?: InputMaybe<StringFilter>;
  outcomesSectionHeading?: InputMaybe<StringFilter>;
  outcomes?: InputMaybe<StringFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type ClarityCoachingConnectionEdges = {
  __typename?: 'ClarityCoachingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ClarityCoaching>;
};

export type ClarityCoachingConnection = Connection & {
  __typename?: 'ClarityCoachingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ClarityCoachingConnectionEdges>>>;
};

export type CareerCoaching = Node & Document & {
  __typename?: 'CareerCoaching';
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  heroCTALabel?: Maybe<Scalars['String']['output']>;
  sectionHeading?: Maybe<Scalars['String']['output']>;
  sectionSubtext?: Maybe<Scalars['String']['output']>;
  situations?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bannerQuote?: Maybe<Scalars['String']['output']>;
  outcomesSectionHeading?: Maybe<Scalars['String']['output']>;
  outcomes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CareerCoachingFilter = {
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  heroCTALabel?: InputMaybe<StringFilter>;
  sectionHeading?: InputMaybe<StringFilter>;
  sectionSubtext?: InputMaybe<StringFilter>;
  situations?: InputMaybe<StringFilter>;
  bannerQuote?: InputMaybe<StringFilter>;
  outcomesSectionHeading?: InputMaybe<StringFilter>;
  outcomes?: InputMaybe<StringFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type CareerCoachingConnectionEdges = {
  __typename?: 'CareerCoachingConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CareerCoaching>;
};

export type CareerCoachingConnection = Connection & {
  __typename?: 'CareerCoachingConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CareerCoachingConnectionEdges>>>;
};

export type Numerology = Node & Document & {
  __typename?: 'Numerology';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroTagline?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  heroCTALabel?: Maybe<Scalars['String']['output']>;
  whatIsHeading?: Maybe<Scalars['String']['output']>;
  whatIsSubtext?: Maybe<Scalars['String']['output']>;
  comparisonText?: Maybe<Scalars['String']['output']>;
  powerText?: Maybe<Scalars['String']['output']>;
  sessionIncludes?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumerologyFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroTagline?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  heroCTALabel?: InputMaybe<StringFilter>;
  whatIsHeading?: InputMaybe<StringFilter>;
  whatIsSubtext?: InputMaybe<StringFilter>;
  comparisonText?: InputMaybe<StringFilter>;
  powerText?: InputMaybe<StringFilter>;
  sessionIncludes?: InputMaybe<StringFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type NumerologyConnectionEdges = {
  __typename?: 'NumerologyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Numerology>;
};

export type NumerologyConnection = Connection & {
  __typename?: 'NumerologyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NumerologyConnectionEdges>>>;
};

export type Resources = Node & Document & {
  __typename?: 'Resources';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroHeadingHighlight?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  blogHeading?: Maybe<Scalars['String']['output']>;
  blogText?: Maybe<Scalars['String']['output']>;
  podcastHeading?: Maybe<Scalars['String']['output']>;
  podcastText?: Maybe<Scalars['String']['output']>;
  ctaSectionHeading?: Maybe<Scalars['String']['output']>;
  ctaSectionSubtext?: Maybe<Scalars['String']['output']>;
  ctaButtonLabel?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResourcesFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroHeadingHighlight?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  blogHeading?: InputMaybe<StringFilter>;
  blogText?: InputMaybe<StringFilter>;
  podcastHeading?: InputMaybe<StringFilter>;
  podcastText?: InputMaybe<StringFilter>;
  ctaSectionHeading?: InputMaybe<StringFilter>;
  ctaSectionSubtext?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
};

export type ResourcesConnectionEdges = {
  __typename?: 'ResourcesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Resources>;
};

export type ResourcesConnection = Connection & {
  __typename?: 'ResourcesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResourcesConnectionEdges>>>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  heroBadge?: Maybe<Scalars['String']['output']>;
  heroHeading?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  responseTime?: Maybe<Scalars['String']['output']>;
  formHeading?: Maybe<Scalars['String']['output']>;
  formSubtext?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactFilter = {
  heroBadge?: InputMaybe<StringFilter>;
  heroHeading?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  responseTime?: InputMaybe<StringFilter>;
  formHeading?: InputMaybe<StringFilter>;
  formSubtext?: InputMaybe<StringFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type TestimonialsItems = {
  __typename?: 'TestimonialsItems';
  quote?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  initials?: Maybe<Scalars['String']['output']>;
};

export type Testimonials = Node & Document & {
  __typename?: 'Testimonials';
  items?: Maybe<Array<Maybe<TestimonialsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsItemsFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  initials?: InputMaybe<StringFilter>;
};

export type TestimonialsFilter = {
  items?: InputMaybe<TestimonialsItemsFilter>;
};

export type TestimonialsConnectionEdges = {
  __typename?: 'TestimonialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials>;
};

export type TestimonialsConnection = Connection & {
  __typename?: 'TestimonialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateAbout: About;
  createAbout: About;
  updateClarityCoaching: ClarityCoaching;
  createClarityCoaching: ClarityCoaching;
  updateCareerCoaching: CareerCoaching;
  createCareerCoaching: CareerCoaching;
  updateNumerology: Numerology;
  createNumerology: Numerology;
  updateResources: Resources;
  createResources: Resources;
  updateContact: Contact;
  createContact: Contact;
  updateTestimonials: Testimonials;
  createTestimonials: Testimonials;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateClarityCoachingArgs = {
  relativePath: Scalars['String']['input'];
  params: ClarityCoachingMutation;
};


export type MutationCreateClarityCoachingArgs = {
  relativePath: Scalars['String']['input'];
  params: ClarityCoachingMutation;
};


export type MutationUpdateCareerCoachingArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerCoachingMutation;
};


export type MutationCreateCareerCoachingArgs = {
  relativePath: Scalars['String']['input'];
  params: CareerCoachingMutation;
};


export type MutationUpdateNumerologyArgs = {
  relativePath: Scalars['String']['input'];
  params: NumerologyMutation;
};


export type MutationCreateNumerologyArgs = {
  relativePath: Scalars['String']['input'];
  params: NumerologyMutation;
};


export type MutationUpdateResourcesArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourcesMutation;
};


export type MutationCreateResourcesArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourcesMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationUpdateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationCreateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  clarityCoaching?: InputMaybe<ClarityCoachingMutation>;
  careerCoaching?: InputMaybe<CareerCoachingMutation>;
  numerology?: InputMaybe<NumerologyMutation>;
  resources?: InputMaybe<ResourcesMutation>;
  contact?: InputMaybe<ContactMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  about?: InputMaybe<AboutMutation>;
  clarityCoaching?: InputMaybe<ClarityCoachingMutation>;
  careerCoaching?: InputMaybe<CareerCoachingMutation>;
  numerology?: InputMaybe<NumerologyMutation>;
  resources?: InputMaybe<ResourcesMutation>;
  contact?: InputMaybe<ContactMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
};

export type HomeMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroHeadingHighlight?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  heroCTALabel?: InputMaybe<Scalars['String']['input']>;
  aboutBadge?: InputMaybe<Scalars['String']['input']>;
  aboutHeading?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph1?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph2?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph3?: InputMaybe<Scalars['String']['input']>;
  aboutQuote?: InputMaybe<Scalars['String']['input']>;
  aboutCTALabel?: InputMaybe<Scalars['String']['input']>;
  servicesSectionHeading?: InputMaybe<Scalars['String']['input']>;
  servicesSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type AboutCredentialsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type AboutValuesMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  desc?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  bioParagraph1?: InputMaybe<Scalars['String']['input']>;
  bioParagraph2?: InputMaybe<Scalars['String']['input']>;
  bioParagraph3?: InputMaybe<Scalars['String']['input']>;
  bioParagraph4?: InputMaybe<Scalars['String']['input']>;
  credentialsSectionHeading?: InputMaybe<Scalars['String']['input']>;
  credentials?: InputMaybe<Array<InputMaybe<AboutCredentialsMutation>>>;
  valuesSectionHeading?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<AboutValuesMutation>>>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type ClarityCoachingPerhapsItemsMutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ClarityCoachingMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  sectionHeading?: InputMaybe<Scalars['String']['input']>;
  sectionSubtext?: InputMaybe<Scalars['String']['input']>;
  perhapsItems?: InputMaybe<Array<InputMaybe<ClarityCoachingPerhapsItemsMutation>>>;
  bannerQuote?: InputMaybe<Scalars['String']['input']>;
  outcomesSectionHeading?: InputMaybe<Scalars['String']['input']>;
  outcomes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type CareerCoachingMutation = {
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  heroCTALabel?: InputMaybe<Scalars['String']['input']>;
  sectionHeading?: InputMaybe<Scalars['String']['input']>;
  sectionSubtext?: InputMaybe<Scalars['String']['input']>;
  situations?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bannerQuote?: InputMaybe<Scalars['String']['input']>;
  outcomesSectionHeading?: InputMaybe<Scalars['String']['input']>;
  outcomes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type NumerologyMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroTagline?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  heroCTALabel?: InputMaybe<Scalars['String']['input']>;
  whatIsHeading?: InputMaybe<Scalars['String']['input']>;
  whatIsSubtext?: InputMaybe<Scalars['String']['input']>;
  comparisonText?: InputMaybe<Scalars['String']['input']>;
  powerText?: InputMaybe<Scalars['String']['input']>;
  sessionIncludes?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type ResourcesMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroHeadingHighlight?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  blogHeading?: InputMaybe<Scalars['String']['input']>;
  blogText?: InputMaybe<Scalars['String']['input']>;
  podcastHeading?: InputMaybe<Scalars['String']['input']>;
  podcastText?: InputMaybe<Scalars['String']['input']>;
  ctaSectionHeading?: InputMaybe<Scalars['String']['input']>;
  ctaSectionSubtext?: InputMaybe<Scalars['String']['input']>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  heroBadge?: InputMaybe<Scalars['String']['input']>;
  heroHeading?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  responseTime?: InputMaybe<Scalars['String']['input']>;
  formHeading?: InputMaybe<Scalars['String']['input']>;
  formSubtext?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialsItemsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  initials?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialsMutation = {
  items?: InputMaybe<Array<InputMaybe<TestimonialsItemsMutation>>>;
};

export type HomePartsFragment = { __typename: 'Home', heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, aboutBadge?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, aboutParagraph3?: string | null, aboutQuote?: string | null, aboutCTALabel?: string | null, servicesSectionHeading?: string | null, servicesSectionSubtext?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null };

export type AboutPartsFragment = { __typename: 'About', heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null, bioParagraph3?: string | null, bioParagraph4?: string | null, credentialsSectionHeading?: string | null, valuesSectionHeading?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, credentials?: Array<{ __typename: 'AboutCredentials', icon?: string | null, title?: string | null, desc?: string | null } | null> | null, values?: Array<{ __typename: 'AboutValues', icon?: string | null, title?: string | null, desc?: string | null } | null> | null };

export type ClarityCoachingPartsFragment = { __typename: 'ClarityCoaching', heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, perhapsItems?: Array<{ __typename: 'ClarityCoachingPerhapsItems', emoji?: string | null, text?: string | null } | null> | null };

export type CareerCoachingPartsFragment = { __typename: 'CareerCoaching', heroHeading?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, situations?: Array<string | null> | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null };

export type NumerologyPartsFragment = { __typename: 'Numerology', heroBadge?: string | null, heroHeading?: string | null, heroTagline?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, whatIsHeading?: string | null, whatIsSubtext?: string | null, comparisonText?: string | null, powerText?: string | null, sessionIncludes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null };

export type ResourcesPartsFragment = { __typename: 'Resources', heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, blogHeading?: string | null, blogText?: string | null, podcastHeading?: string | null, podcastText?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null };

export type ContactPartsFragment = { __typename: 'Contact', heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, email?: string | null, location?: string | null, responseTime?: string | null, formHeading?: string | null, formSubtext?: string | null };

export type TestimonialsPartsFragment = { __typename: 'Testimonials', items?: Array<{ __typename: 'TestimonialsItems', quote?: string | null, name?: string | null, role?: string | null, initials?: string | null } | null> | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, aboutBadge?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, aboutParagraph3?: string | null, aboutQuote?: string | null, aboutCTALabel?: string | null, servicesSectionHeading?: string | null, servicesSectionSubtext?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, aboutBadge?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, aboutParagraph3?: string | null, aboutQuote?: string | null, aboutCTALabel?: string | null, servicesSectionHeading?: string | null, servicesSectionSubtext?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null, bioParagraph3?: string | null, bioParagraph4?: string | null, credentialsSectionHeading?: string | null, valuesSectionHeading?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, credentials?: Array<{ __typename: 'AboutCredentials', icon?: string | null, title?: string | null, desc?: string | null } | null> | null, values?: Array<{ __typename: 'AboutValues', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null, bioParagraph3?: string | null, bioParagraph4?: string | null, credentialsSectionHeading?: string | null, valuesSectionHeading?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, credentials?: Array<{ __typename: 'AboutCredentials', icon?: string | null, title?: string | null, desc?: string | null } | null> | null, values?: Array<{ __typename: 'AboutValues', icon?: string | null, title?: string | null, desc?: string | null } | null> | null } | null } | null> | null } };

export type ClarityCoachingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ClarityCoachingQuery = { __typename?: 'Query', clarityCoaching: { __typename: 'ClarityCoaching', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, perhapsItems?: Array<{ __typename: 'ClarityCoachingPerhapsItems', emoji?: string | null, text?: string | null } | null> | null } };

export type ClarityCoachingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ClarityCoachingFilter>;
}>;


export type ClarityCoachingConnectionQuery = { __typename?: 'Query', clarityCoachingConnection: { __typename?: 'ClarityCoachingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ClarityCoachingConnectionEdges', cursor: string, node?: { __typename: 'ClarityCoaching', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, perhapsItems?: Array<{ __typename: 'ClarityCoachingPerhapsItems', emoji?: string | null, text?: string | null } | null> | null } | null } | null> | null } };

export type CareerCoachingQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CareerCoachingQuery = { __typename?: 'Query', careerCoaching: { __typename: 'CareerCoaching', id: string, heroHeading?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, situations?: Array<string | null> | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CareerCoachingConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CareerCoachingFilter>;
}>;


export type CareerCoachingConnectionQuery = { __typename?: 'Query', careerCoachingConnection: { __typename?: 'CareerCoachingConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CareerCoachingConnectionEdges', cursor: string, node?: { __typename: 'CareerCoaching', id: string, heroHeading?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, situations?: Array<string | null> | null, bannerQuote?: string | null, outcomesSectionHeading?: string | null, outcomes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NumerologyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NumerologyQuery = { __typename?: 'Query', numerology: { __typename: 'Numerology', id: string, heroBadge?: string | null, heroHeading?: string | null, heroTagline?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, whatIsHeading?: string | null, whatIsSubtext?: string | null, comparisonText?: string | null, powerText?: string | null, sessionIncludes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NumerologyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NumerologyFilter>;
}>;


export type NumerologyConnectionQuery = { __typename?: 'Query', numerologyConnection: { __typename?: 'NumerologyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NumerologyConnectionEdges', cursor: string, node?: { __typename: 'Numerology', id: string, heroBadge?: string | null, heroHeading?: string | null, heroTagline?: string | null, heroSubtext?: string | null, heroCTALabel?: string | null, whatIsHeading?: string | null, whatIsSubtext?: string | null, comparisonText?: string | null, powerText?: string | null, sessionIncludes?: Array<string | null> | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ResourcesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResourcesQuery = { __typename?: 'Query', resources: { __typename: 'Resources', id: string, heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, blogHeading?: string | null, blogText?: string | null, podcastHeading?: string | null, podcastText?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResourcesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourcesFilter>;
}>;


export type ResourcesConnectionQuery = { __typename?: 'Query', resourcesConnection: { __typename?: 'ResourcesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResourcesConnectionEdges', cursor: string, node?: { __typename: 'Resources', id: string, heroBadge?: string | null, heroHeading?: string | null, heroHeadingHighlight?: string | null, heroSubtext?: string | null, blogHeading?: string | null, blogText?: string | null, podcastHeading?: string | null, podcastText?: string | null, ctaSectionHeading?: string | null, ctaSectionSubtext?: string | null, ctaButtonLabel?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, email?: string | null, location?: string | null, responseTime?: string | null, formHeading?: string | null, formSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, heroBadge?: string | null, heroHeading?: string | null, heroSubtext?: string | null, email?: string | null, location?: string | null, responseTime?: string | null, formHeading?: string | null, formSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialsQuery = { __typename?: 'Query', testimonials: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TestimonialsItems', quote?: string | null, name?: string | null, role?: string | null, initials?: string | null } | null> | null } };

export type TestimonialsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
}>;


export type TestimonialsConnectionQuery = { __typename?: 'Query', testimonialsConnection: { __typename?: 'TestimonialsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialsConnectionEdges', cursor: string, node?: { __typename: 'Testimonials', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'TestimonialsItems', quote?: string | null, name?: string | null, role?: string | null, initials?: string | null } | null> | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  heroBadge
  heroHeading
  heroHeadingHighlight
  heroSubtext
  heroCTALabel
  aboutBadge
  aboutHeading
  aboutParagraph1
  aboutParagraph2
  aboutParagraph3
  aboutQuote
  aboutCTALabel
  servicesSectionHeading
  servicesSectionSubtext
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  bioParagraph1
  bioParagraph2
  bioParagraph3
  bioParagraph4
  credentialsSectionHeading
  credentials {
    __typename
    icon
    title
    desc
  }
  valuesSectionHeading
  values {
    __typename
    icon
    title
    desc
  }
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const ClarityCoachingPartsFragmentDoc = gql`
    fragment ClarityCoachingParts on ClarityCoaching {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  sectionHeading
  sectionSubtext
  perhapsItems {
    __typename
    emoji
    text
  }
  bannerQuote
  outcomesSectionHeading
  outcomes
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const CareerCoachingPartsFragmentDoc = gql`
    fragment CareerCoachingParts on CareerCoaching {
  __typename
  heroHeading
  heroSubtext
  heroCTALabel
  sectionHeading
  sectionSubtext
  situations
  bannerQuote
  outcomesSectionHeading
  outcomes
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const NumerologyPartsFragmentDoc = gql`
    fragment NumerologyParts on Numerology {
  __typename
  heroBadge
  heroHeading
  heroTagline
  heroSubtext
  heroCTALabel
  whatIsHeading
  whatIsSubtext
  comparisonText
  powerText
  sessionIncludes
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const ResourcesPartsFragmentDoc = gql`
    fragment ResourcesParts on Resources {
  __typename
  heroBadge
  heroHeading
  heroHeadingHighlight
  heroSubtext
  blogHeading
  blogText
  podcastHeading
  podcastText
  ctaSectionHeading
  ctaSectionSubtext
  ctaButtonLabel
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  heroBadge
  heroHeading
  heroSubtext
  email
  location
  responseTime
  formHeading
  formSubtext
}
    `;
export const TestimonialsPartsFragmentDoc = gql`
    fragment TestimonialsParts on Testimonials {
  __typename
  items {
    __typename
    quote
    name
    role
    initials
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ClarityCoachingDocument = gql`
    query clarityCoaching($relativePath: String!) {
  clarityCoaching(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ClarityCoachingParts
  }
}
    ${ClarityCoachingPartsFragmentDoc}`;
export const ClarityCoachingConnectionDocument = gql`
    query clarityCoachingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ClarityCoachingFilter) {
  clarityCoachingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ClarityCoachingParts
      }
    }
  }
}
    ${ClarityCoachingPartsFragmentDoc}`;
export const CareerCoachingDocument = gql`
    query careerCoaching($relativePath: String!) {
  careerCoaching(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CareerCoachingParts
  }
}
    ${CareerCoachingPartsFragmentDoc}`;
export const CareerCoachingConnectionDocument = gql`
    query careerCoachingConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CareerCoachingFilter) {
  careerCoachingConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CareerCoachingParts
      }
    }
  }
}
    ${CareerCoachingPartsFragmentDoc}`;
export const NumerologyDocument = gql`
    query numerology($relativePath: String!) {
  numerology(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NumerologyParts
  }
}
    ${NumerologyPartsFragmentDoc}`;
export const NumerologyConnectionDocument = gql`
    query numerologyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NumerologyFilter) {
  numerologyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NumerologyParts
      }
    }
  }
}
    ${NumerologyPartsFragmentDoc}`;
export const ResourcesDocument = gql`
    query resources($relativePath: String!) {
  resources(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResourcesParts
  }
}
    ${ResourcesPartsFragmentDoc}`;
export const ResourcesConnectionDocument = gql`
    query resourcesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResourcesFilter) {
  resourcesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResourcesParts
      }
    }
  }
}
    ${ResourcesPartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export const TestimonialsDocument = gql`
    query testimonials($relativePath: String!) {
  testimonials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsParts
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TestimonialsConnectionDocument = gql`
    query testimonialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsFilter) {
  testimonialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsParts
      }
    }
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    clarityCoaching(variables: ClarityCoachingQueryVariables, options?: C): Promise<{data: ClarityCoachingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClarityCoachingQueryVariables, query: string}> {
        return requester<{data: ClarityCoachingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClarityCoachingQueryVariables, query: string}, ClarityCoachingQueryVariables>(ClarityCoachingDocument, variables, options);
      },
    clarityCoachingConnection(variables?: ClarityCoachingConnectionQueryVariables, options?: C): Promise<{data: ClarityCoachingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClarityCoachingConnectionQueryVariables, query: string}> {
        return requester<{data: ClarityCoachingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ClarityCoachingConnectionQueryVariables, query: string}, ClarityCoachingConnectionQueryVariables>(ClarityCoachingConnectionDocument, variables, options);
      },
    careerCoaching(variables: CareerCoachingQueryVariables, options?: C): Promise<{data: CareerCoachingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerCoachingQueryVariables, query: string}> {
        return requester<{data: CareerCoachingQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerCoachingQueryVariables, query: string}, CareerCoachingQueryVariables>(CareerCoachingDocument, variables, options);
      },
    careerCoachingConnection(variables?: CareerCoachingConnectionQueryVariables, options?: C): Promise<{data: CareerCoachingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerCoachingConnectionQueryVariables, query: string}> {
        return requester<{data: CareerCoachingConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CareerCoachingConnectionQueryVariables, query: string}, CareerCoachingConnectionQueryVariables>(CareerCoachingConnectionDocument, variables, options);
      },
    numerology(variables: NumerologyQueryVariables, options?: C): Promise<{data: NumerologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NumerologyQueryVariables, query: string}> {
        return requester<{data: NumerologyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NumerologyQueryVariables, query: string}, NumerologyQueryVariables>(NumerologyDocument, variables, options);
      },
    numerologyConnection(variables?: NumerologyConnectionQueryVariables, options?: C): Promise<{data: NumerologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NumerologyConnectionQueryVariables, query: string}> {
        return requester<{data: NumerologyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NumerologyConnectionQueryVariables, query: string}, NumerologyConnectionQueryVariables>(NumerologyConnectionDocument, variables, options);
      },
    resources(variables: ResourcesQueryVariables, options?: C): Promise<{data: ResourcesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesQueryVariables, query: string}> {
        return requester<{data: ResourcesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesQueryVariables, query: string}, ResourcesQueryVariables>(ResourcesDocument, variables, options);
      },
    resourcesConnection(variables?: ResourcesConnectionQueryVariables, options?: C): Promise<{data: ResourcesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesConnectionQueryVariables, query: string}> {
        return requester<{data: ResourcesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourcesConnectionQueryVariables, query: string}, ResourcesConnectionQueryVariables>(ResourcesConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      },
    testimonials(variables: TestimonialsQueryVariables, options?: C): Promise<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}> {
        return requester<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}, TestimonialsQueryVariables>(TestimonialsDocument, variables, options);
      },
    testimonialsConnection(variables?: TestimonialsConnectionQueryVariables, options?: C): Promise<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}, TestimonialsConnectionQueryVariables>(TestimonialsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  