---
# cPanel deployment configuration
# Copies only explicit files and directories to the cPanel public_html path.
deployment:
  tasks:
    - export DEPLOYPATH=/home/innerjourneywith/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp blog.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
  - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
  - /bin/cp email-config.php $DEPLOYPATH
  - /bin/cp php.ini $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R scripts $DEPLOYPATH
    # Ensure public-readable permissions for deployed files
    - /bin/chmod -R 755 $DEPLOYPATH
