/**
 * Builds a cut-down Font Awesome that contains only the icons this site uses.
 *
 * The full Font Awesome webfonts are ~230 KB and were the largest download on
 * every page. This keeps the same `fas fa-*` / `fab fa-*` markup but ships a
 * subset font (a few KB) and a stylesheet with only the matching icon rules.
 *
 * Icons included: every id in lib/icons.ts (so anything Shanila can pick in
 * Tina works) plus every `fa-*` name written in app/ and components/.
 *
 * Run after adding an icon:  npm run build-icons
 * Needs Python fonttools (`pip install fonttools brotli`) for pyftsubset.
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { ICONS } from '../lib/icons'

const ROOT = path.resolve(__dirname, '..')
const FA = path.join(ROOT, 'node_modules/@fortawesome/fontawesome-free')
const OUT_FONTS = path.join(ROOT, 'public/fonts/fa')
const OUT_CSS = path.join(ROOT, 'styles/icons.css')
const FONTS = ['fa-solid-900', 'fa-brands-400']
const CODE_DIRS = ['app', 'components']
/** `fa-*` strings in code that are not icons. */
const NOT_ICONS = new Set(['fa-solid', 'fa-css'])

function walk(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) return walk(p)
    return /\.(tsx?|jsx?)$/.test(e.name) ? [p] : []
  })
}

export function usedIconNames(): string[] {
  const names = new Set(ICONS.map((i) => i.id))
  for (const dir of CODE_DIRS) {
    for (const file of walk(path.join(ROOT, dir))) {
      for (const m of fs.readFileSync(file, 'utf8').matchAll(/\bfa-[a-z0-9-]+/g)) {
        if (!NOT_ICONS.has(m[0])) names.add(m[0])
      }
    }
  }
  return [...names].sort()
}

function main() {
  const css = fs.readFileSync(path.join(FA, 'css/all.min.css'), 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')
  const names = usedIconNames()
  const wanted = new Set(names.map((n) => `.${n}:before`))
  const codepoints = new Set<string>()
  const found = new Set<string>()

  // all.min.css is flat: at-rules, then `selectors{declarations}` rules.
  const rules = css.match(/@font-face\{[^}]*\}|@[^{]+\{(?:[^{}]*\{[^}]*\})*[^}]*\}|[^{}@]+\{[^}]*\}/g) ?? []
  const kept: string[] = []
  const faces = new Set<string>()
  for (const rule of rules) {
    if (rule.startsWith('@font-face')) {
      const font = FONTS.find((f) => rule.includes(`${f}.woff2`))
      if (font && !faces.has(font) && faces.add(font)) kept.push(`@font-face{font-family:"${font.includes('brands') ? 'Font Awesome 6 Brands' : 'Font Awesome 6 Free'}";font-style:normal;font-weight:${font.includes('brands') ? 400 : 900};font-display:block;src:url(/fonts/fa/${font}.woff2) format("woff2")}`)
      continue
    }
    const [selectorText, body] = rule.split('{')
    const content = body.match(/^content:"\\([0-9a-f]+)"\}$/)
    if (!content) {
      // Base classes, sizes, animations — keep, minus the v4/v5 compat and duotone/regular noise.
      if (!/fa-regular|\.far|fa-duotone|\.fad|fa-light|\.fal|fa-thin|fa-v4/.test(selectorText) || /\.fas|\.fab|\.fa\b/.test(selectorText)) kept.push(rule)
      continue
    }
    const selectors = selectorText.split(',').filter((s) => wanted.has(s))
    if (!selectors.length) continue
    selectors.forEach((s) => found.add(s.slice(1, -':before'.length)))
    codepoints.add(content[1])
    kept.push(`${selectors.join(',')}{${body}`)
  }

  const missing = names.filter((n) => !found.has(n))
  if (missing.length) throw new Error(`Not in Font Awesome 6.0 free: ${missing.join(', ')}`)

  fs.mkdirSync(OUT_FONTS, { recursive: true })
  const unicodes = [...codepoints].map((c) => `U+${c}`).join(',')
  for (const font of FONTS) {
    execFileSync('pyftsubset', [
      path.join(FA, `webfonts/${font}.ttf`),
      `--unicodes=${unicodes}`,
      '--flavor=woff2',
      '--layout-features=*',
      '--no-hinting',
      `--output-file=${path.join(OUT_FONTS, `${font}.woff2`)}`,
    ])
  }

  const header = `/* Generated by scripts/build-icon-font.ts (Font Awesome Free 6.0.0, CC BY 4.0 / SIL OFL 1.1). Do not edit. */\n`
  fs.writeFileSync(OUT_CSS, header + kept.join('\n') + '\n')
  const kb = (f: string) => (fs.statSync(f).size / 1024).toFixed(1)
  console.log(`${names.length} icons → ${OUT_CSS} (${kb(OUT_CSS)} KB)`)
  for (const font of FONTS) console.log(`  ${font}.woff2 ${kb(path.join(OUT_FONTS, `${font}.woff2`))} KB`)
}

if (require.main === module) main()
